spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${DB_NAME:buyora}
    username: ${DB_USERNAME:buyora}
    password: ${DB_PASSWORD}
    hikari:
      initialization-fail-timeout: 60000
      connection-timeout: 30000
  data:
    redis:
      host: redis
      port: 6379
  mail:
    host: ${MAIL_HOST:mailpit}
    port: ${MAIL_PORT:1025}
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
  lifecycle:
    timeout-per-shutdown-phase: 20s
server:
  shutdown: graceful
logging:
  level:
    root: INFO
    com.buyora.api: INFO
